version: "3"
services:
  tf-flask:
    build: .
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./app:/app
    command: python -u app.py
    environment:
      - PYTHONUNBUFFERED=1
