version: "3"
services:
  tf-flask:
    build: .
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./app:/app
    command: uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi:app
    environment:
      - PYTHONUNBUFFERED=1
